Add missing 'chai-as-promised' dependency
When I attempted to run e2e tests I got following error:

```
$npm run test:e2e

> magicmirror@2.1.1 test:e2e /Users/sergeym/localDev/MagicMirror
> ./node_modules/mocha/bin/mocha tests/e2e --recursive

module.js:471
    throw err;
    ^

Error: Cannot find module 'chai-as-promised'
...
```

Adding `chai-as-promised` to `package.json` and running npm install fixes it.